//
//  SourceKitUIDS.swift
//  SwiftSourceKit
//

import sourcekitd

let KeyRequest = sourcekitd_uid_get_from_cstr("key.request")
let KeyCompilerArgs = sourcekitd_uid_get_from_cstr("key.compilerargs")
let KeyOffset = sourcekitd_uid_get_from_cstr("key.offset")
let KeySourceFile = sourcekitd_uid_get_from_cstr("key.sourcefile")
let KeyModuleName = sourcekitd_uid_get_from_cstr("key.modulename")
let KeyName = sourcekitd_uid_get_from_cstr("key.name")
let KeyFilePath = sourcekitd_uid_get_from_cstr("key.filepath")
let KeyModuleInterfaceName = sourcekitd_uid_get_from_cstr("key.module_interface_name")
let KeyLength = sourcekitd_uid_get_from_cstr("key.length")
let KeySourceText = sourcekitd_uid_get_from_cstr("key.sourcetext")
let KeyUSR = sourcekitd_uid_get_from_cstr("key.usr")
let KeyTypename = sourcekitd_uid_get_from_cstr("key.typename")
let KeyOverrides = sourcekitd_uid_get_from_cstr("key.overrides")
let KeyRelatedDecls = sourcekitd_uid_get_from_cstr("key.related_decls")
let KeyAnnotatedDecl = sourcekitd_uid_get_from_cstr("key.annotated_decl")
let KeyDocFullAsXML = sourcekitd_uid_get_from_cstr("key.doc.full_as_xml")
let KeyResults = sourcekitd_uid_get_from_cstr("key.results")
let KeySyntaxMap = sourcekitd_uid_get_from_cstr("key.syntaxmap")
let KeyEnableSyntaxMap = sourcekitd_uid_get_from_cstr("key.enablesyntaxmap")
let KeyEnableSubStructure = sourcekitd_uid_get_from_cstr("key.enablesubstructure")
let KeySyntacticOnly = sourcekitd_uid_get_from_cstr("key.syntactic_only")
let KeyLine = sourcekitd_uid_get_from_cstr("key.line")
let KeyFormatOptions = sourcekitd_uid_get_from_cstr("key.editor.format.options")
let KeyCodeCompleteOptions =
    sourcekitd_uid_get_from_cstr("key.codecomplete.options")
let KeyKind = sourcekitd_uid_get_from_cstr("key.kind")
let KeyAnnotations = sourcekitd_uid_get_from_cstr("key.annotations")
let KeyDiagnostics = sourcekitd_uid_get_from_cstr("key.diagnostics")
let KeyDiagnosticStage = sourcekitd_uid_get_from_cstr("key.diagnostic_stage")
let KeySubStructure = sourcekitd_uid_get_from_cstr("key.substructure")
let KeyIsSystem = sourcekitd_uid_get_from_cstr("key.is_system")
let KeyNotification = sourcekitd_uid_get_from_cstr("key.notification")
let KeyPopular = sourcekitd_uid_get_from_cstr("key.popular")
let KeyUnpopular = sourcekitd_uid_get_from_cstr("key.unpopular")
let KeyTypeInterface = sourcekitd_uid_get_from_cstr("key.typeinterface")

let RequestIndex = sourcekitd_uid_get_from_cstr("source.request.indexsource")
let RequestCodeComplete = sourcekitd_uid_get_from_cstr("source.request.codecomplete")
let RequestCodeCompleteOpen = sourcekitd_uid_get_from_cstr("source.request.codecomplete.open")
let RequestCodeCompleteClose = sourcekitd_uid_get_from_cstr("source.request.codecomplete.close")
let RequestCodeCompleteUpdate = sourcekitd_uid_get_from_cstr("source.request.codecomplete.update")
let RequestCodeCompleteCacheOnDisk = sourcekitd_uid_get_from_cstr("source.request.codecomplete.cache.ondisk")
let RequestCodeCompleteSetPopularAPI = sourcekitd_uid_get_from_cstr("source.request.codecomplete.setpopularapi")
let RequestCursorInfo = sourcekitd_uid_get_from_cstr("source.request.cursorinfo")
let RequestRelatedIdents = sourcekitd_uid_get_from_cstr("source.request.relatedidents")
let RequestEditorOpen = sourcekitd_uid_get_from_cstr("source.request.editor.open")
let RequestEditorOpenInterface = sourcekitd_uid_get_from_cstr("source.request.editor.open.interface")
let RequestEditorOpenSwiftSourceInterface = sourcekitd_uid_get_from_cstr("source.request.editor.open.interface.swiftsource")
let RequestEditorOpenHeaderInterface = sourcekitd_uid_get_from_cstr("source.request.editor.open.interface.header")
let RequestEditorExtractTextFromComment = sourcekitd_uid_get_from_cstr("source.request.editor.extract.comment")
let RequestEditorReplaceText = sourcekitd_uid_get_from_cstr("source.request.editor.replacetext")
let RequestEditorFormatText = sourcekitd_uid_get_from_cstr("source.request.editor.formattext")
let RequestEditorExpandPlaceholder = sourcekitd_uid_get_from_cstr("source.request.editor.expand_placeholder")
let RequestEditorFindUSR = sourcekitd_uid_get_from_cstr("source.request.editor.find_usr")
let RequestEditorFindInterfaceDoc = sourcekitd_uid_get_from_cstr("source.request.editor.find_interface_doc")
let RequestDocInfo = sourcekitd_uid_get_from_cstr("source.request.docinfo")

let NotificationDocumentUpdate = sourcekitd_uid_get_from_cstr("source.notification.editor.documentupdate")

let SourceLangSwiftKeyword = sourcekitd_uid_get_from_cstr("source.lang.swift.syntaxtype.keyword")
let SourceLangSwiftIdentifier = sourcekitd_uid_get_from_cstr("source.lang.swift.syntaxtype.identifier")
let SourceLangSwiftNumber = sourcekitd_uid_get_from_cstr("source.lang.swift.syntaxtype.number")
let SourceLangSwiftString = sourcekitd_uid_get_from_cstr("source.lang.swift.syntaxtype.string")
let SourceLangSwiftComment = sourcekitd_uid_get_from_cstr("source.lang.swift.syntaxtype.comment")